package controllers

import (
	"net/http"

	qcontrollers "gitlab.com/beacon-software/quimby/controllers"
	"gitlab.com/beacon-software/quimby/example/config"
	"gitlab.com/beacon-software/quimby/example/security"
	qhttp "gitlab.com/beacon-software/quimby/http"
)

// DocController renders the autogenerated api documentation
type DocController struct {
	qcontrollers.MethodNotAllowedController
	qcontrollers.BasicAuthenticatedController
	Specification *config.Specification
}

// NewDocController returns an initialized DocController
func NewDocController(spec *config.Specification) *DocController {
	controller := &DocController{Specification: spec}
	controller.Validator = security.NewBasicValidator()

	return controller
}

// GetRoutes establishes routes for the RegistrationsController
func (controller *DocController) GetRoutes() []string {
	return []string{
		"1/docs",
	}
}

// Get renders the documentation HTML
func (controller *DocController) Get(context *qhttp.Context) {
	context.Response.Header().Add("Content-Type", "text/html")
	context.SetResponse(htmlDocs, http.StatusOK)
}
